apiVersion: v1
kind: Service
metadata:
  name: take-my-money-web
  namespace: default
  labels:
    app: take-my-money-web
spec:
  type: ClusterIP
  selector:
    app: take-my-money-web
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
  # Session affinity for consistent routing
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
