apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: take-my-money-production

commonLabels:
  app: take-my-money-web
  environment: production

bases:
  - ../

patches:
  - target:
      kind: Deployment
      name: take-my-money-web
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 5
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 500m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 512Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 1000m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 1Gi

  - target:
      kind: HorizontalPodAutoscaler
      name: take-my-money-web-hpa
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 5
      - op: replace
        path: /spec/maxReplicas
        value: 20

configMapGenerator:
  - name: take-my-money-config
    behavior: merge
    literals:
      - api_url="https://api.take-my-money.com"
      - log_level="warn"
