apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: last-key-staging

commonLabels:
  app: last-key-web
  environment: staging

bases:
  - ../

patches:
  - target:
      kind: Deployment
      name: last-key-web
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2

  - target:
      kind: HorizontalPodAutoscaler
      name: last-key-web-hpa
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 2
      - op: replace
        path: /spec/maxReplicas
        value: 5

configMapGenerator:
  - name: last-key-config
    behavior: merge
    literals:
      - api_url="https://api-staging.last-key.com"
      - log_level="info"
